name: model-fermented-grape-juice-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python ContinuousIntegrationML.py
          
          echo "##Model metrics">report.md
          cat FermetedGrapeJuiceScores.txt >>report.md
          
          echo "##Data Visualize" >> report.md
          cml.publish Feature_importance.png --md >> report.md
          cml.publish residuals.png --md >> report.md
